### ISSUE TITLE
Task Prioritization

### ISSUE THREAD

**Issue by ira-halenok** [AutomatedProcessImprovement/Prosimos#43]
The idea is the next one:

> when the task is being added to the Priority Queue, we can assign a different priority to them.

Before: we were assigning the enabled time as the value for priority. This way, we were saying that the oldest tasks are being executed in the first place. 

Now, we have a set of rules defining the task's different priority values.
The set of rules is composed based on the `case attributes` or `activity name`.

Changes: 
before putting the task to the queue, we check its priority (execute the newly written function), and after that, we assign the received priority number to the task. If two tasks have the same priority level, then we decide the order based on the enabled time.

The structure of the rules remains similar to the one we have for batching:
we have two inherited arrays. The first one specifies OR rules, and the inherited one specifies the rules combined with an AND operator. 

Uniform distribution for categorical.
What should be the default priority?

design
domain model -> class diagram 

verification -> testing, execution times measurement

Components:
 case attributes' generation
 condition evaluation
 case priority assignment
 case based activity prioritisation

Task List [12/01]:
- [x] parse and save the prioritisation in the state
- [x] calculate the priority of each case (case-based prioritisation)
- [x] add the priority of each task when assigning it to the resource. Expected behavior: the already build Python queue will decide internally the order of the task execution
- [ ] develop the test template on how we can validate the right execution of the task based on the priority 

Questions:

- Prioritisation of the tasks that are inside the batch? 

-

**Comment by david-chapela** [comment]
Here you have a simple example for the JSON parameters for prioritization. Feel free to adapt it if a different format is better for you, or ping me for any other doubt!

By default, the lower the priority level, the more priority the activity has.

[priorit_json_template.txt](https://github.com/AutomatedProcessImprovement/Prosimos/files/10347605/priorit_json_template.txt)
