### ISSUE TITLE
Introduce Case Attributes

### ISSUE THREAD

**Issue by ira-halenok** [AutomatedProcessImprovement/Prosimos#44]
Case Attributes are the ones used to describe the case in general.

We need to allow adding the case attributes in the resulting log file.
As input, we receive a new .json section describing each log case attribute.

Prosimos uses this description and adds all case attributes in the log file.
Since they describe the case, we can calculate values for all case attributes right at the beginning (when we calculate the start time of a case).

**Comment by david-chapela** [comment]
Here you have a simple example with two case attributes, one discrete and one continuous. Just a guide, so if you want to adapt anything from there, feel free to do it!

[case_attrib_json_template.txt](https://github.com/AutomatedProcessImprovement/Prosimos/files/10347620/case_attrib_json_template.txt)

**Comment by ira-halenok** [comment]
@david-chapela the only small change from my side at the moment: changing the map with dynamic keys to the array of objects so that it looks like this: 

```
"values": [
  {"key": "REGULAR", "probability": 0.8 },
  {"key": "BUSINESS", "probability": 0.2 }
]
```
